"""criação das tabelas iniciais

Revision ID: 11ee2a40cacc
Revises: 
Create Date: 2025-09-23 17:47:21.066208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ee2a40cacc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_rafa_TB_Categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_finance_rafa_TB_Categories_id'),
                    'finance_rafa_TB_Categories', ['id'], unique=False)
    op.create_index(op.f('ix_finance_rafa_TB_Categories_name'),
                    'finance_rafa_TB_Categories', ['name'], unique=True)

    op.create_table('finance_rafa_TB_Reports',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('total_income', sa.Float(), nullable=True),
                    sa.Column('total_expense', sa.Float(), nullable=True),
                    sa.Column('balance', sa.Float(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['finance_rafa_TB_Reports.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_finance_rafa_TB_Reports_id'),
                    'finance_rafa_TB_Reports', ['id'], unique=False)
    op.create_table('finance_rafa_TB_Users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('cpf', sa.String(length=11), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cpf')
                    )
    op.create_index(op.f('ix_finance_rafa_TB_Users_email'),
                    'finance_rafa_TB_Users', ['email'], unique=True)
    op.create_index(op.f('ix_finance_rafa_TB_Users_id'),
                    'finance_rafa_TB_Users', ['id'], unique=False)
    op.create_table('finance_rafa_TB_Transactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['finance_rafa_TB_Categories.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['finance_rafa_TB_Users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_finance_rafa_TB_Transactions_id'),
                    'finance_rafa_TB_Transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_rafa_TB_Transactions_id'),
                  table_name='finance_rafa_TB_Transactions')
    op.drop_table('finance_rafa_TB_Transactions')
    op.drop_index(op.f('ix_finance_rafa_TB_Users_id'),
                  table_name='finance_rafa_TB_Users')
    op.drop_index(op.f('ix_finance_rafa_TB_Users_email'),
                  table_name='finance_rafa_TB_Users')
    op.drop_table('finance_rafa_TB_Users')
    op.drop_index(op.f('ix_finance_rafa_TB_Reports_id'),
                  table_name='finance_rafa_TB_Reports')
    op.drop_table('finance_rafa_TB_Reports')
    op.drop_index(op.f('ix_finance_rafa_TB_Categories_name'),
                  table_name='finance_rafa_TB_Categories')
    op.drop_index(op.f('ix_finance_rafa_TB_Categories_id'),
                  table_name='finance_rafa_TB_Categories')
    op.drop_table('finance_rafa_TB_Categories')
    # ### end Alembic commands ###
