"""add user_id fk to reports

Revision ID: 6f5afbc0ad14
Revises: 195eff51fe87
Create Date: 2025-09-24 13:41:16.238271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5afbc0ad14'
down_revision: Union[str, Sequence[str], None] = '195eff51fe87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_rafa_TB_Reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('finance_rafa_TB_Transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_rafa_TB_Transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('finance_rafa_TB_Reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
