"""add user_id to reports

Revision ID: a2f583d881fc
Revises: 11ee2a40cacc
Create Date: 2025-09-24 09:44:11.531605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f583d881fc'
down_revision: Union[str, Sequence[str], None] = '11ee2a40cacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_rafa_TB_Reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('finance_rafa_TB_Reports_user_id_fkey'), 'finance_rafa_TB_Reports', type_='foreignkey')
    op.create_foreign_key(None, 'finance_rafa_TB_Reports', 'finance_rafa_TB_Users', ['user_id'], ['id'])
    op.alter_column('finance_rafa_TB_Transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_rafa_TB_Transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'finance_rafa_TB_Reports', type_='foreignkey')
    op.create_foreign_key(op.f('finance_rafa_TB_Reports_user_id_fkey'), 'finance_rafa_TB_Reports', 'finance_rafa_TB_Reports', ['user_id'], ['id'])
    op.alter_column('finance_rafa_TB_Reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
